<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Error Handling on Virtual World</title>
    <link>http://www.jiaqili.me/tags/error-handling/</link>
    <description>Recent content in Error Handling on Virtual World</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en</language>
    <lastBuildDate>Sun, 02 Sep 2018 19:05:00 +0800</lastBuildDate>
    
	<atom:link href="http://www.jiaqili.me/tags/error-handling/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>Java基础知识系列11：断言和异常</title>
      <link>http://www.jiaqili.me/post/java-basics-11-exception/</link>
      <pubDate>Sun, 02 Sep 2018 19:05:00 +0800</pubDate>
      
      <guid>http://www.jiaqili.me/post/java-basics-11-exception/</guid>
      <description>&lt;p&gt;Java 中有三种处理错误的机制：异常(Exception)、断言(Assertion) 和日志(Log)。这里介绍前两种。&lt;/p&gt;

&lt;h1 id=&#34;断言&#34;&gt;断言&lt;/h1&gt;

&lt;p&gt;断言的格式&lt;code&gt;assert &amp;lt;condition&amp;gt;&lt;/code&gt;或者&lt;code&gt;assert &amp;lt;condition&amp;gt; : &amp;lt;expression&amp;gt;&lt;/code&gt;&lt;/p&gt;

&lt;p&gt;上述两种形式的断言都会对条件进行检测，如果是false，则会抛出AssertionError异常。第二种带有表达式的断言仅仅是把表达式的内容传递给AssertionError以便之后处理，比如打印出来。比如：&lt;/p&gt;

&lt;pre&gt;&lt;code class=&#34;language-java&#34;&gt;int x = 0;
assert x &amp;gt; 0 : &amp;quot;Now you see my assetion message.&amp;quot;;
&lt;/code&gt;&lt;/pre&gt;

&lt;p&gt;为了看到Assertion的报错，我们需要打开虚拟机的参数-ea，上述代码会输出：&lt;/p&gt;

&lt;p&gt;&lt;/p&gt;</description>
    </item>
    
  </channel>
</rss>