<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Java基础知识系列11：断言和异常 - Virtual World</title>
  <meta name="renderer" content="webkit" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>

<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />

<meta name="theme-color" content="#f8f5ec" />
<meta name="msapplication-navbutton-color" content="#f8f5ec">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="#f8f5ec">


<meta name="author" content="Jiaqi Li" />
  <meta name="description" content="Java 中有三种处理错误的机制：异常(Exception)、断言(Assertion) 和日志(Log)。这里介绍前两种。
断言 断言的格式assert &amp;lt;condition&amp;gt;或者assert &amp;lt;condition&amp;gt; : &amp;lt;expression&amp;gt;
上述两种形式的断言都会对条件进行检测，如果是false，则会抛出AssertionError异常。第二种带有表达式的断言仅仅是把表达式的内容传递给AssertionError以便之后处理，比如打印出来。比如：
int x = 0; assert x &amp;gt; 0 : &amp;quot;Now you see my assetion message.&amp;quot;;  为了看到Assertion的报错，我们需要打开虚拟机的参数-ea，上述代码会输出：

" />







<meta name="generator" content="Hugo 0.41" />


<link rel="canonical" href="http://www.jiaqili.me/post/java-basics-11-exception/" />

<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="icon" href="/favicon.ico" />
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">







<link href="/dist/even.min.css?v=2.7.1" rel="stylesheet">
<link href="/lib/fancybox/jquery.fancybox-3.1.20.min.css" rel="stylesheet">

<meta property="og:title" content="Java基础知识系列11：断言和异常" />
<meta property="og:description" content="Java 中有三种处理错误的机制：异常(Exception)、断言(Assertion) 和日志(Log)。这里介绍前两种。

断言

断言的格式assert &lt;condition&gt;或者assert &lt;condition&gt; : &lt;expression&gt;

上述两种形式的断言都会对条件进行检测，如果是false，则会抛出AssertionError异常。第二种带有表达式的断言仅仅是把表达式的内容传递给AssertionError以便之后处理，比如打印出来。比如：

int x = 0;
assert x &gt; 0 : &quot;Now you see my assetion message.&quot;;


为了看到Assertion的报错，我们需要打开虚拟机的参数-ea，上述代码会输出：

" />
<meta property="og:type" content="article" />
<meta property="og:url" content="http://www.jiaqili.me/post/java-basics-11-exception/" />



<meta property="article:published_time" content="2018-09-02T19:05:00&#43;08:00"/>

<meta property="article:modified_time" content="2018-09-02T19:05:00&#43;08:00"/>











<meta itemprop="name" content="Java基础知识系列11：断言和异常">
<meta itemprop="description" content="Java 中有三种处理错误的机制：异常(Exception)、断言(Assertion) 和日志(Log)。这里介绍前两种。

断言

断言的格式assert &lt;condition&gt;或者assert &lt;condition&gt; : &lt;expression&gt;

上述两种形式的断言都会对条件进行检测，如果是false，则会抛出AssertionError异常。第二种带有表达式的断言仅仅是把表达式的内容传递给AssertionError以便之后处理，比如打印出来。比如：

int x = 0;
assert x &gt; 0 : &quot;Now you see my assetion message.&quot;;


为了看到Assertion的报错，我们需要打开虚拟机的参数-ea，上述代码会输出：

">


<meta itemprop="datePublished" content="2018-09-02T19:05:00&#43;08:00" />
<meta itemprop="dateModified" content="2018-09-02T19:05:00&#43;08:00" />
<meta itemprop="wordCount" content="4083">



<meta itemprop="keywords" content="Java,Error handling," />
<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Java基础知识系列11：断言和异常"/>
<meta name="twitter:description" content="Java 中有三种处理错误的机制：异常(Exception)、断言(Assertion) 和日志(Log)。这里介绍前两种。

断言

断言的格式assert &lt;condition&gt;或者assert &lt;condition&gt; : &lt;expression&gt;

上述两种形式的断言都会对条件进行检测，如果是false，则会抛出AssertionError异常。第二种带有表达式的断言仅仅是把表达式的内容传递给AssertionError以便之后处理，比如打印出来。比如：

int x = 0;
assert x &gt; 0 : &quot;Now you see my assetion message.&quot;;


为了看到Assertion的报错，我们需要打开虚拟机的参数-ea，上述代码会输出：

"/>

<!--[if lte IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/classlist/1.1.20170427/classList.min.js"></script>
<![endif]-->

<!--[if lt IE 9]>
  <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
<![endif]-->

</head>
<body>
  <div id="mobile-navbar" class="mobile-navbar">
  <div class="mobile-header-logo">
    <a href="/" class="logo">Virtual World</a>
  </div>
  <div class="mobile-navbar-icon">
    <span></span>
    <span></span>
    <span></span>
  </div>
</div>
<nav id="mobile-menu" class="mobile-menu slideout-menu">
  <ul class="mobile-menu-list">
    <a href="/">
        <li class="mobile-menu-item">Home</li>
      </a><a href="/post/">
        <li class="mobile-menu-item">Archives</li>
      </a><a href="/tags/">
        <li class="mobile-menu-item">Tags</li>
      </a><a href="/categories/">
        <li class="mobile-menu-item">Categories</li>
      </a><a href="/about/">
        <li class="mobile-menu-item">About</li>
      </a>
  </ul>
</nav>
  <div class="container" id="mobile-panel">
    <header id="header" class="header">
        <div class="logo-wrapper">
  <a href="/" class="logo">Virtual World</a>
</div>

<nav class="site-navbar">
  <ul id="menu" class="menu">
    <li class="menu-item">
        <a class="menu-item-link" href="/">Home</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/post/">Archives</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/tags/">Tags</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/categories/">Categories</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/about/">About</a>
      </li>
  </ul>
</nav>
    </header>

    <main id="main" class="main">
      <div class="content-wrapper">
        <div id="content" class="content">
          <article class="post">
    
    <header class="post-header">
      <h1 class="post-title">Java基础知识系列11：断言和异常</h1>

      <div class="post-meta">
        <span class="post-time"> 2018-09-02 </span>
        <div class="post-category">
            
              <a href="/categories/java/"> Java </a>
            
          </div>
        <span class="more-meta"> 4083 word </span>
        <span class="more-meta"> 9 min read </span>
        
      </div>
    </header>

    
    
<div class="post-toc" id="post-toc">
  <h2 class="post-toc-title">Contents</h2>
  
  <div class="post-toc-content">
    <nav id="TableOfContents">
<ul>
<li><a href="#断言">断言</a></li>
<li><a href="#异常">异常</a>
<ul>
<li><a href="#抛出异常">抛出异常</a></li>
<li><a href="#捕获异常">捕获异常</a></li>
<li><a href="#栈分析">栈分析</a></li>
</ul></li>
</ul>
</nav>
  </div>
</div>

    
    <div class="post-content">
      <p>Java 中有三种处理错误的机制：异常(Exception)、断言(Assertion) 和日志(Log)。这里介绍前两种。</p>

<h1 id="断言">断言</h1>

<p>断言的格式<code>assert &lt;condition&gt;</code>或者<code>assert &lt;condition&gt; : &lt;expression&gt;</code></p>

<p>上述两种形式的断言都会对条件进行检测，如果是false，则会抛出AssertionError异常。第二种带有表达式的断言仅仅是把表达式的内容传递给AssertionError以便之后处理，比如打印出来。比如：</p>

<pre><code class="language-java">int x = 0;
assert x &gt; 0 : &quot;Now you see my assetion message.&quot;;
</code></pre>

<p>为了看到Assertion的报错，我们需要打开虚拟机的参数-ea，上述代码会输出：</p>

<p></p>

<pre><code class="language-text">Exception in thread &quot;main&quot; java.lang.AssertionError: Now you see my assetion message.
</code></pre>

<p>断言只用于在开发测试期间，向代码中插入的一些检测语句，以便定位程序内部错误。断言失败是致命的、不可恢复的错误。但是我们不用在程序发布时移除断言代码，因为默认情况下断言是被禁用的。启用和禁用断言是类加载器的工作，所以我们不需要重新编译代码。启用和禁用（默认）所有断言的虚拟机参数为-ea和-da：</p>

<pre><code class="language-Shell">java -ea MyApp
java -da MyApp
</code></pre>

<p>我们也可以启用部分类的断言：</p>

<pre><code class="language-shell">java -ea:MyClass -ea:com.example... MyApp
</code></pre>

<p>这里我们启用了MyClass类和com.example包及其子包中所有类的断言。我们也可以禁用部分断言：</p>

<pre><code class="language-shell">java -ea:... -da:MyClass
</code></pre>

<p>那些Java系统的类的没有类加载器，需要使用-enablesystemassertion/-esa 参数来启用。</p>

<h1 id="异常">异常</h1>

<p>所有异常继承自Throwable类。Throwable类下面分为Error和Exception两个子类。</p>

<ol>
<li>Error类，描述了Java运行时系统内部的错误，或者资源耗尽的情况，应用程序不应该抛出这种类的对象。</li>
<li>Exception下面又有一个RuntimeException的子类，它描述的是程序错误导致的异常，比如空指针，数组越界等。Exception下的其它子类描述的是非程序错误导致的异常，比如IOException等。
派生于Error和RuntimeException的类的所有异常称为未检查异常，其它的异常称为已检查异常，编译器确保对于所有已检查异常提供了异常处理器。</li>
</ol>

<p>这里所有的异常，包括Error和Exception，都是发生在运行时的，不仅仅是RuntimeException。</p>

<h2 id="抛出异常">抛出异常</h2>

<p>如果一个方法调用了会抛出已检查异常的方法，或这个方法本身会throw出一个已检查异常的，并且该方法并没有捕获这个异常，那么就要在该方法的首部申明所有的这些异常类。未检查的异常要么不可控制（Error），要么应避免发生（RuntimeException）。如下：</p>

<pre><code class="language-java">public void method() throws IOException {}
</code></pre>

<p>如果一个方法声明可能会抛出一个异常，它可能会抛出这个异常的对象或该异常子类异常的对象。比如上面的method方法，它可能抛出的是一个IOException也可能是其子类异常，比如FileNotFoundException异常的对象。</p>

<p>如果子类中覆盖了父类的方法，子类中可以抛出更特定的异常，或者根本不抛出异常，但是不能抛出比父类更加通用的异常。这和继承相反，异常范围随着继承变小。
一个出现在父类的方法的异常申明，不一定会出现在其子类的同名方法中。如果将子类向上转型为父类，那么编译器会要求你处理父类的（更大范围的）异常。</p>

<p>如果父类方法中没有抛出任何已检查异常，那么子类也不能抛出任何已检查异常。还有一种情况，如果类A继承了类B并且实现了接口C，而B和C有同名方法分别抛出异常X和Y，那么类A的该方法中X和Y都不可以抛。
因为扩展类方法的异常范围小于等于每一个父类和每一个父接口中该方法声明的异常。但是我们可以把它包装成一个RuntimeException抛出，后面会提到。</p>

<p>这里异常的限制对构造器不起作用。子类构造器可以抛出任意异常而不用关心父类构造器抛出了什么异常，但是因为父类构造器肯定会被子类调用，所以子类构造器的异常声明必需包含父类构造器的异常申明。子类构造器不能捕获父类构造器抛出的异常。</p>

<p>异常本身并不是方法签名的一部分，不能基于异常说明来重载方法。</p>

<p>抛出异常的语法如下，所有标准异常类都有一个默认构造器和一个接收字符串作为参数的构造器：</p>

<pre><code class="language-java">throw new Exception(&quot;Error␣message&quot;);
</code></pre>

<p>我们也可以自定义异常类。自定义异常类最重要的是类的名字，因为类的名字通常已经表述了异常发生的原因。自定义的异常类必需派生自Exception或其子类。一般包含两个构造器，一个无参构造器，一个带有详细信息描述的构造器。</p>

<pre><code class="language-java">class MyException extends IOException{
    public MyException(){}
    public MyException(String msg){
        super(msg);
    }
}
</code></pre>

<h2 id="捕获异常">捕获异常</h2>

<p>try&hellip;catch语句块的执行顺序：</p>

<ol>
<li>如果try语句块中的代码未抛出异常，程序将跳过catch子句继续执行剩下的代码；</li>
<li>如果try语句块中的代码抛出了在catch子句中声明的异常，程序将跳过try语句块中剩下的代码，执行对应catch异常处理器中的代码，然后继续执行catch之后的代码。异常处理机制负责匹配与异常类型一致的第一个异常处理器，一旦匹配catch字句结束，不再继续搜索异常处理器。所以一般范围大的基类Exception被放在后面；</li>
<li>如果try语句块中抛出了catch中未声明的异常，或者try之外的地方抛出了异常，那么这个方法会立即结束，错误被抛给调用者。</li>
</ol>

<p>如果调用了一个会抛出已检查异常的方法或方法自身会抛出已检查异常，在知道如何处理的情况下才能捕获它进行处理，否则就应该继续传递这个异常。如果覆盖了父类的方法，而这个方法没有抛出异常，那么这个方法就必须捕获每一个已检查异常，或者包装成RuntimeException抛出。</p>

<p>可以通过多个catch子句捕获多个异常，一般特定的范围小的异常在前面，范围大的异常在后面，如果异常没有继承关系，则无所谓。如果颠倒这种关系，会报不可达错误。捕获的异常可以通过getMessage()获得异常的详细原因，或者e.getClass().getName()获取异常对象的实际类型。如下所示：</p>

<pre><code class="language-java">try{
// ...
}catch(FileNotFoundException e){
    System.out.println(e.getMessage());
}catch(IOException e){
    System.out.println(e.getMessage());
}catch(Exception e){
    System.out.println(e.getMessage());
}
</code></pre>

<p>Java 7以后可以将彼此间不存在继承关系的异常合并到一个catch 子句中：</p>

<pre><code class="language-java">try{
    // ...
}catch(FileNotFoundException | UnknownHostException e){
    // ...
}
</code></pre>

<p>捕获多个异常的时候，异常对象e隐含为final类型，不能在其子句中再次赋值。</p>

<p>我们可以在catch中再次抛出异常。这可能发生在我们只需要记录错误，但不处理错误，即抛出同一个异常；或者为了改变异常的类型。后者通常发生在一个子模块出错的时候，我们不想知道具体的细节，只需要知道这个模块发生了错误。这个时候我们将原始异常设置为新异常的原因，然后抛出新的异常。这种打包的方式可以让我们抛出更高级别的异常，而同时保留了底异常的信息。示例如下：</p>

<pre><code class="language-java">try{
    // ...
}catch(SQLException e){
    Throwable t = new MySubsystemException(&quot;Database␣error&quot;);
    t.initCause(e);
    throw t;
}
</code></pre>

<p>用这种方法我们可以实现前面所提到的，在一个不能抛出已检查异常的方法中，需要抛出异常时，可以重新打包成一个RuntimeException然后抛出。</p>

<p>在Java 7中，如果catch语句再次抛出了一个声明范围大于方法声明抛出异常范围的异常时，比如下面代码，编译器会检查try语句块中实际可能抛出的异常，如果实际可能抛出的异常范围符合方法的声明范围，则没有问题。</p>

<pre><code class="language-java">public void update() throws SQLException{
    try{
    // ... This might throw an SQLException
    }catch(Exception e){
    // ...
    throw e; // OK because try block can only throw SQLException
    }
}
</code></pre>

<p>try&hellip;catch&hellip;finally语句块的执行顺序：</p>

<ol>
<li><p>try中的代码没有异常。程序会执行完try的语句，然后执行finally中的语句，然后继续执行finally之后的语句。</p></li>

<li><p>try中抛出在catch被捕获的异常。程序会执行try语句中的代码，直到抛出异常的语句为止。然后跳过try中剩余的代码，转去执行对应catch中的代码，然后执行finally中的代码。
如果catch中再次抛出了异常，并且没有被捕获，那么这个方法在finally代码被执行后立即结束，异常被抛给这个方法的调用者；如果catch没有再次抛出异常，则在finally执行完成后继续执行finally之后的语句。</p></li>

<li><p>try中抛出了不能被catch捕获的异常。程序会执行try语句中的代码，直到抛出异常的语句为止。然后跳过try中剩余的代码，执行finally里的代码，然后方法结束，异常被抛给调用者。</p></li>
</ol>

<p>try语句也可以没有catch，只有finally。这时候当遇到异常时，finally语句执行后，异常会被再次抛出。</p>

<p><strong>警告</strong>: 如果try语句和finally语句都有return语句，并且try语句执行到了return，然后跳转到finally继续执行return，那么后者的返回值将覆盖前者的返回值。</p>

<p><strong>警告</strong>：如果try语句抛出异常，finally语句也抛出异常，那么try语句的异常将会丢失。对于这种情况，在Java 6及以前，我们需要用如下复杂的代码来实现<code>优先抛出try，再考虑finally</code>：</p>

<pre><code class="language-java">InputStream in = ...;
Exception ex = null;

try{
    try{
        // ...
    }catch(Exception e){
        ex = e;
        throw e;
    }
}finally{
    try{
        in.close();
    }catch(Exception e){
        if(ex == null) throw e;
    }
}
</code></pre>

<p>而在Java 7中我们可以使用try-with-resources语句块。任何实现了AutoCloseable接口的类都可以被作为这里的资源放在try语句块后面的括号里：</p>

<pre><code class="language-java">try(Resource1 res1 = ...; Resource2 res2 = ...){
    // ...
}
</code></pre>

<p>当try 正常退出或者抛出异常时，res1和res2 的close()方法都会被调用。如果try和close都抛出异常，那么try的异常会被重新抛出，close抛出的异常会被抑制：通过addSuppressed方法添加到try的异常中。</p>

<p>如果对这些被抑制的异常感兴趣，可以调用getSuppressed获取。try-with-resource语句也可以有catch和finally，它们会在资源关闭后执行。如果需要关闭资源，建议都使用try-with-resource。</p>

<h2 id="栈分析">栈分析</h2>

<p>以下给出了三种堆栈跟踪的方法：</p>

<pre><code class="language-java">public static void main(String[] args) {

    System.out.println(&quot;Calling printStackTrace()&quot;);
    try{
        ok();
    }catch(Exception e){
        StringWriter sw = new StringWriter();
        PrintWriter pw = new PrintWriter(sw);
        e.printStackTrace(pw);
        System.out.println(sw.toString());
    }
    
    System.out.println(&quot;Calling getStackTrace()&quot;);
    try{
        ok();
    }catch(Exception e){
        StackTraceElement[] frames = e.getStackTrace();
        for(StackTraceElement f : frames){
            System.out.println(f);
        }
    }
    
    System.out.println(&quot;Calling getAllStackTraces()&quot;);
    try{
        ok();
    }catch(Exception e){
        Map &lt;Thread, StackTraceElement[]&gt; map = Thread.getAllStackTraces();
        
        for(Thread t : map.keySet()){
            StackTraceElement[] frames = map.get(t);
            System.out.println(&quot;Thread: &quot; + t.getName());
            
            for(StackTraceElement f : frames){
                System.out.println(&quot;    &quot; + f);
            }
        }
    }
}

public static void ok () throws IOException{
    throw new IOException(&quot;Oops..&quot;);
}

</code></pre>

<p>它们的输出如下：</p>

<pre><code class="language-text">Calling printStackTrace()
java.io.IOException: Oops..
at Test9.ok(Test9.java:47)
at Test9.main(Test9.java:12)
Calling getStackTrace()
Test9.ok(Test9.java:47)
Test9.main(Test9.java:22)
Calling getAllStackTraces()
Thread: Signal Dispatcher
Thread: main
java.lang.Thread.dumpThreads(Native Method)
java.lang.Thread.getAllStackTraces(Thread.java:1603)
Test9.main(Test9.java:34)
Thread: Attach Listener
Thread: Finalizer
java.lang.Object.wait(Native Method)
java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)
Thread: Reference Handler
java.lang.Object.wait(Native Method)
java.lang.Object.wait(Object.java:502)
java.lang.ref.Reference.tryHandlePending(Reference.java:191)
java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)
</code></pre>
    </div>

    
    
<div class="post-copyright">
  <p class="copyright-item">
    <span class="item-title">Author</span>
    <span class="item-content">Jiaqi Li</span>
  </p>
  <p class="copyright-item">
    <span class="item-title">LastMod</span>
    <span class="item-content">2018-09-02</span>
  </p>
  
  <p class="copyright-item">
    <span class="item-title">License</span>
    <span class="item-content"><a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.</span>
  </p>
</div>

    
    

    <footer class="post-footer">
      <div class="post-tags">
          
          <a href="/tags/java/">Java</a>
          
          <a href="/tags/error-handling/">Error handling</a>
          
        </div>

      
      <nav class="post-nav">
        
          <a class="prev" href="/post/java-basics-12-database/">
            <i class="iconfont icon-left"></i>
            <span class="prev-text nav-default">Java基础知识系列12：数据库编程</span>
            <span class="prev-text nav-mobile">Prev</span>
          </a>
        
          <a class="next" href="/post/java-basics-10-container/">
            <span class="next-text nav-default">Java基础知识系列10：容器</span>
            <span class="prev-text nav-mobile">Next</span>
            <i class="iconfont icon-right"></i>
          </a>
      </nav>
    </footer>
  </article>
        </div>
        
  

  

  
      </div>
    </main>

    <footer id="footer" class="footer">
      <div class="social-links">
      <a href="https://www.facebook.com/ajl98" class="iconfont icon-facebook" title="facebook"></a>
      <a href="https://www.instagram.com/binaryexplorer/" class="iconfont icon-instagram" title="instagram"></a>
      <a href="https://www.linkedin.com/in/alexjiaqili/" class="iconfont icon-linkedin" title="linkedin"></a>
      <a href="https://github.com/virtworld" class="iconfont icon-github" title="github"></a>
  <a href="http://www.jiaqili.me/index.xml" type="application/rss+xml" class="iconfont icon-rss" title="rss"></a>
</div>

<div class="copyright">
  <span class="power-by">
    Powered by <a class="hexo-link" href="https://gohugo.io">Hugo</a>
  </span>
  <span class="division">|</span>
  <span class="theme-info">
    Theme - 
    <a class="theme-link" href="https://github.com/olOwOlo/hugo-theme-even">Even</a>
  </span>

  

  <span class="copyright-year">
    &copy; 
    
      2014 - 
    2018
    <span class="heart">
      <i class="iconfont icon-heart"></i>
    </span>
    <span class="author">Jiaqi Li</span>
  </span>
</div>
    </footer>

    <div class="back-to-top" id="back-to-top">
      <i class="iconfont icon-up"></i>
    </div>
  </div>
  
<script src="/lib/highlight/highlight.pack.js?v=20171001"></script>
<script type="text/javascript" src="/lib/jquery/jquery-3.2.1.min.js"></script>
  <script type="text/javascript" src="/lib/slideout/slideout-1.0.1.min.js"></script>
  <script type="text/javascript" src="/lib/fancybox/jquery.fancybox-3.1.20.min.js"></script>
<script type="text/javascript" src="/dist/even.min.js?v=2.7.1"></script>
  <script type="text/javascript">
    window.MathJax = {
      showProcessingMessages: false,
      messageStyle: 'none'
    };
  </script>
  <script async src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'></script>




</body>
</html>
